bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

diet_exercise_app/urls.py
from django.urls import path
from . import views

app_name = 'diet_exercise_app'

urlpatterns = [
    path('create_diet_plan/', views.create_diet_plan, name='create_diet_plan'),
    path('view_diet_plan/', views.view_diet_plan, name='view_diet_plan'),
    path('create_exercise_plan/', views.create_exercise_plan, name='create_exercise_plan'),
    path('view_exercise_plan/', views.view_exercise_plan, name='view_exercise_plan'),
]

project_5/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('profile/', include('profiles.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('diet_exercise/', include('diet_exercise_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/main-nav.html
<div class="collapse navbar-collapse" id="main-nav">
    <ul class="navbar-nav w-auto mx-auto">
        <li class="nav-item dropdown">
            <a class="logo-font font-weight-bold nav-link text-black mr-5" href="#" id="all-products-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                all products
            </a>
            <div class="dropdown-menu border-0" aria-labelledby="all-products-link">
                <a href="{% url 'products' %}?sort=price&direction=acs" class="dropdown-item">By Price</a>
                <a href="{% url 'products' %}?sort=rating&direction=desc" class="dropdown-item">By Rating</a>
                <a href="{% url 'products' %}?sort=category&direction=acs" class="dropdown-item">By Catagories</a>
                <a href="{% url 'products' %}" class="dropdown-item">All Products</a>
            </div>
        </li>

        <li class="nav-item dropdown">
            <a class="logo-font font-weight-bold nav-link text-black mr-5" href="#" id="clothing-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                clothing
            </a>
            <div class="dropdown-menu border-0" aria-labelledby="all-products-link">
                <a href="{% url 'products' %}?category=tops" class="dropdown-item">Tops</a>
                <a href="{% url 'products' %}?category=bottoms" class="dropdown-item">Bottoms</a>
                <a href="{% url 'products' %}?category=sets" class="dropdown-item">Sets</a>
                <a href="{% url 'products' %}?category=tops,bottoms,sets" class="dropdown-item">All Clothing</a>
            </div>
        </li>

        <li class="nav-item dropdown">
            <a class="logo-font font-weight-bold nav-link text-black mr-5" href="#" id="clothing-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                gym
            </a>
            <div class="dropdown-menu border-0" aria-labelledby="all-products-link">
                <a href="{% url 'products' %}?category=bags" class="dropdown-item">Bags</a>
                <a href="{% url 'products' %}?category=bottles" class="dropdown-item">Bottles</a>
                <a href="{% url 'products' %}?category=straps" class="dropdown-item">Straps</a>
                <a href="{% url 'products' %}?category=bags,bottles,straps" class="dropdown-item">All Gym</a>
            </div>
        </li>

        <li class="nav-item dropdown">
            <a class="logo-font font-weight-bold nav-link text-black mr-5" href="#" id="clothing-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                equipment
            </a>
            <div class="dropdown-menu border-0" aria-labelledby="all-products-link">
                <a href="{% url 'products' %}?category=weights" class="dropdown-item">Weights</a>
                <a href="{% url 'products' %}?category=cardio" class="dropdown-item">Cardio</a>
                <a href="{% url 'products' %}?category=home" class="dropdown-item">Home</a>
                <a href="{% url 'products' %}?category=weights,cardio,home" class="dropdown-item">All Equipment</a>
            </div>
        </li>

        <li class="nav-item dropdown">
            <a class="logo-font font-weight-bold nav-link text-black mr-5" href="#" id="clothing-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                diet & exercise plans
            </a>
            <div class="dropdown-menu border-0" aria-labelledby="specials-link">
                <a href="{% url 'diet_exercise_app:create_diet_plan' %}" class="dropdown-item">Create Diet Plan</a>
                <a href="{% url 'diet_exercise_app:view_diet_plan' %}" class="dropdown-item">View Diet Plans</a>
                <a href="{% url 'diet_exercise_app:create_exercise_plan' %}" class="dropdown-item">Create Exercise Plan</a>
                <a href="{% url 'diet_exercise_app:view_exercise_plan' %}" class="dropdown-item">View Exercise Plans</a>
            </div>
        </li>
        
    </ul>
</div>

templates/includes/mobile-top-header.html
<!--button to open search-->
<li class="list-inline-item">
    <a class="text-black nav-link d-block d-lg-none" href="#" id="mobile-search" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <div class="text-center">
            <div><i class="fas fa-search fa-lg"></i></div>
            <p class="my-0">Search</p>
        </div>
    </a>
    <div class="dropdown-menu border-0 w-100 p-3 rounded-0 my-0" aria-labelledby="mobile-search">
        <form class="form" method="GET" action="{% url 'products' %}">
            <div class="input-group w-100">
                <input class="form-control border border-black rounded-0" type="text" name="q" placeholder="Search our site">
                <div class="input-group-append">
                    <button class="form-control form-control btn btn-black border border-black rounded-0" type="submit">
                        <span class="icon">
                            <i class="fas fa-search"></i>
                        </span>
                    </button>
                </div>
            </div>
        </form>
    </div>
</li>
<!--open my account dropdown-->
<li class="list-inline-item dropdown">
    <a class="text-black nav-link d-block d-lg-none" href="#" id="user-options" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <div class="text-center">
            <div><i class="fas fa-user fa-lg"></i></div>
            <p class="my-0">Account</p>
        </div>
    </a>
    <div class="dropdown-menu border-0" aria-labelledby="user-options">
        {% if request.user.is_authenticated %}
            {% if request.user.is_superuser %}
                <a href="{% url 'account_logout' %}" class="dropdown-item">Product Management</a>
            {% endif %}
            <a href="" class="dropdown-item">My Profile</a>
            <a href="{% url 'account_logout' %}" class="dropdown-item">Logout</a>
        {% else %}
            <a href="{% url 'account_signup' %}" class="dropdown-item">Register</a>
            <a href="{% url 'account_login' %}" class="dropdown-item">Login</a>
        {% endif %}
    </div>
</li>
<!--open shopping bag-->
<li class="list-inline-item">
    <a class="{% if grand_total %}text-primary font-weight-bold{% else %}text-black{% endif %} nav-link d-block d-lg-none" href="{% url 'view_bag' %}">
        <div class="text-center">
            <div><i class="fas fa-shopping-bag fa-lg"></i></div>
            <p class="my-0">
                {% if grand_total %}
                    ${{ grand_total|floatformat:2 }}
                {% else %}
                    $0.00
                {% endif %}
            </p>
        </div>
    </a>
</li>